*:******************************************************************************
*:
*: Procedure File Z:\TIM\DOCUMENTATION\TIMCCLOG.PRG
*:
*:	Carl Pratt
*:	Cornerstones Electrical Services, Inc.
*:	PO Box 2138
*:	Sandy
*:	Utah
*:	84091
*:	USA
*:	
*:	
*:	
*:	
*:	
*:	
*:
*: Documented using Visual FoxPro Formatting wizard version  .05
*:******************************************************************************
*:   TIMCCLOG
Use TIMCCLOG
Do TIMCCLOG.spr
Return
