*:*****************************************************************************
*:
*:        Program: C:\TIM\PRG\TIMINV.PRG
*:         System: TIM ( TRUCK INVENTORY MAINTENANCE)
*:         Author: CARL PRATT
*:      Copyright (c) 01/28/97, CARL PRATT
*:  Last modified: 08/29/93 at  9:31:52
*:
*:      Called by: TIMDISPA.PRG                      
*:
*:      Documented 12:30:51                                FoxDoc version 3.00a
*:*****************************************************************************


*: EOF: TIMINV.PRG
